//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_Master
    {
        public long Add_ID { get; set; }
        public long User_ID { get; set; }
        public string Add_Address { get; set; }
        public long Cityid { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public Nullable<long> added_by { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual City_Master City_Master { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
