//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_Master
    {
        public long Add_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string Add_Address { get; set; }
        public string CityName { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
