//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset_Master()
        {
            this.Asset_Movement = new HashSet<Asset_Movement>();
        }
    
        public long Asset_id { get; set; }
        public long Company_ID { get; set; }
        public long Asset_Type { get; set; }
        public string Asset_Name { get; set; }
        public string Detail { get; set; }
        public System.DateTime Purchase_Date { get; set; }
        public Nullable<int> Service_Duration { get; set; }
        public Nullable<long> Currently_User { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Asset_type Asset_type1 { get; set; }
        public virtual Company_Master Company_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Movement> Asset_Movement { get; set; }
    }
}
