//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Movement
    {
        public long Movement_id { get; set; }
        public long Asset_id { get; set; }
        public Nullable<long> From_id { get; set; }
        public Nullable<long> To_id { get; set; }
        public System.DateTime Movement_Date { get; set; }
        public string Detail { get; set; }
    
        public virtual Asset_Master Asset_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
