//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Master
    {
        public long Attendance_id { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Punch_Date { get; set; }
        public Nullable<decimal> Attendance { get; set; }
        public Nullable<decimal> TotalHrs { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
