//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Master
    {
        public long Comnt_ID { get; set; }
        public long Task_Id { get; set; }
        public long Emp_Id { get; set; }
        public string Comments { get; set; }
        public System.DateTime Commented_Date { get; set; }
        public long Comment_Type { get; set; }
        public Nullable<long> Add_By { get; set; }
        public Nullable<System.DateTime> Add_On { get; set; }
    
        public virtual Project_Task_Master Project_Task_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
