//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Menu_Rights
    {
        public long Company_Rights_Id { get; set; }
        public long Company_ID { get; set; }
        public bool Employees { get; set; }
        public bool Assets { get; set; }
        public bool Task { get; set; }
        public bool NoticeBoard { get; set; }
        public bool Attendance { get; set; }
        public bool Vouchers { get; set; }
        public bool Document_Storage { get; set; }
        public bool Document_Generator { get; set; }
        public bool Salary_Generator { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
