//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Doc_Heads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Doc_Heads()
        {
            this.Company_Doc_Heads2 = new HashSet<Company_Doc_Heads2>();
        }
    
        public long Document_HeadId { get; set; }
        public long Company_ID { get; set; }
        public string HeadName { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Doc_Heads2> Company_Doc_Heads2 { get; set; }
    }
}
