//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Doc_Heads2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Doc_Heads2()
        {
            this.Company_ImportantDocuments = new HashSet<Company_ImportantDocuments>();
        }
    
        public long Document_Head2Id { get; set; }
        public long Document_HeadId { get; set; }
        public string HeadName { get; set; }
    
        public virtual Company_Doc_Heads Company_Doc_Heads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_ImportantDocuments> Company_ImportantDocuments { get; set; }
    }
}
