//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_ImportantDocuments
    {
        public long Document_Id { get; set; }
        public long Company_ID { get; set; }
        public long Document_HeadId { get; set; }
        public long Document_Head2Id { get; set; }
        public Nullable<System.DateTime> DMonth { get; set; }
        public string DName { get; set; }
        public string DURL { get; set; }
        public Nullable<System.DateTime> DAddedon { get; set; }
        public string DUploadby { get; set; }
    
        public virtual Company_Doc_Heads2 Company_Doc_Heads2 { get; set; }
    }
}
