//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Document
    {
        public long Cust_Id { get; set; }
        public long Company_ID { get; set; }
        public string Doc_Name { get; set; }
        public string Doc_Disc { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
