//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Prod_Satyamgroup_V1Entities : DbContext
    {
        public Prod_Satyamgroup_V1Entities()
            : base("name=Prod_Satyamgroup_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_Master> Address_Master { get; set; }
        public virtual DbSet<Asset_Master> Asset_Master { get; set; }
        public virtual DbSet<Asset_Movement> Asset_Movement { get; set; }
        public virtual DbSet<Asset_type> Asset_type { get; set; }
        public virtual DbSet<Attendance_Master> Attendance_Master { get; set; }
        public virtual DbSet<City_Master> City_Master { get; set; }
        public virtual DbSet<Comment_Master> Comment_Master { get; set; }
        public virtual DbSet<Company_Doc_Heads> Company_Doc_Heads { get; set; }
        public virtual DbSet<Company_Doc_Heads2> Company_Doc_Heads2 { get; set; }
        public virtual DbSet<Company_Doc_Master> Company_Doc_Master { get; set; }
        public virtual DbSet<Company_ImportantDocuments> Company_ImportantDocuments { get; set; }
        public virtual DbSet<Company_Master> Company_Master { get; set; }
        public virtual DbSet<Company_Menu_Rights> Company_Menu_Rights { get; set; }
        public virtual DbSet<Custom_Document> Custom_Document { get; set; }
        public virtual DbSet<Department_Master> Department_Master { get; set; }
        public virtual DbSet<Designation_Master> Designation_Master { get; set; }
        public virtual DbSet<Document_Master> Document_Master { get; set; }
        public virtual DbSet<Education_Master> Education_Master { get; set; }
        public virtual DbSet<Employee_Task_Master> Employee_Task_Master { get; set; }
        public virtual DbSet<Event_Master> Event_Master { get; set; }
        public virtual DbSet<Experience_Master> Experience_Master { get; set; }
        public virtual DbSet<Festival_Master> Festival_Master { get; set; }
        public virtual DbSet<FollowUp_Master> FollowUp_Master { get; set; }
        public virtual DbSet<Generated_Documents> Generated_Documents { get; set; }
        public virtual DbSet<Gift_Master> Gift_Master { get; set; }
        public virtual DbSet<Head_Master> Head_Master { get; set; }
        public virtual DbSet<Holiday_Master> Holiday_Master { get; set; }
        public virtual DbSet<Imp_Doc_Master> Imp_Doc_Master { get; set; }
        public virtual DbSet<Inquiry_Master> Inquiry_Master { get; set; }
        public virtual DbSet<Leave_Master> Leave_Master { get; set; }
        public virtual DbSet<Master_Token> Master_Token { get; set; }
        public virtual DbSet<NoticeBoard_Master> NoticeBoard_Master { get; set; }
        public virtual DbSet<Project_Assign_Master> Project_Assign_Master { get; set; }
        public virtual DbSet<Project_Master> Project_Master { get; set; }
        public virtual DbSet<Project_Task_Master> Project_Task_Master { get; set; }
        public virtual DbSet<ProjectSalary> ProjectSalaries { get; set; }
        public virtual DbSet<ProjectSalaryGroup> ProjectSalaryGroups { get; set; }
        public virtual DbSet<ProjectSalaryHead> ProjectSalaryHeads { get; set; }
        public virtual DbSet<Punch_Type> Punch_Type { get; set; }
        public virtual DbSet<Relation_Master> Relation_Master { get; set; }
        public virtual DbSet<Religion_Master> Religion_Master { get; set; }
        public virtual DbSet<Request_Master> Request_Master { get; set; }
        public virtual DbSet<Resignation_Master> Resignation_Master { get; set; }
        public virtual DbSet<Shift_Master> Shift_Master { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<Transaction_Master> Transaction_Master { get; set; }
        public virtual DbSet<User_Menu_Rights> User_Menu_Rights { get; set; }
        public virtual DbSet<User_Punch> User_Punch { get; set; }
        public virtual DbSet<User_Visits> User_Visits { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Voucher_Master> Voucher_Master { get; set; }
    
        public virtual ObjectResult<DashboardEMP_Result> DashboardEMP(Nullable<int> userid, Nullable<int> company_Id)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var company_IdParameter = company_Id.HasValue ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardEMP_Result>("DashboardEMP", useridParameter, company_IdParameter);
        }
    
        public virtual int Delete_Company(Nullable<long> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Company", companyIDParameter);
        }
    
        public virtual int Delete_Employee(Nullable<long> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Employee", employeeIDParameter);
        }
    
        public virtual ObjectResult<GetCity_Result> GetCity(Nullable<long> cityID, string searchtext, string sortColumn, string sortDirection, Nullable<long> pageSize, Nullable<long> pageNumber)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(long));
    
            var searchtextParameter = searchtext != null ?
                new ObjectParameter("Searchtext", searchtext) :
                new ObjectParameter("Searchtext", typeof(string));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(long));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCity_Result>("GetCity", cityIDParameter, searchtextParameter, sortColumnParameter, sortDirectionParameter, pageSizeParameter, pageNumberParameter);
        }
    
        public virtual ObjectResult<GetCommericalDocuments_Result> GetCommericalDocuments(Nullable<long> company_ID, Nullable<long> document_HeadId, Nullable<long> document_Head2Id, Nullable<System.DateTime> dMonth)
        {
            var company_IDParameter = company_ID.HasValue ?
                new ObjectParameter("Company_ID", company_ID) :
                new ObjectParameter("Company_ID", typeof(long));
    
            var document_HeadIdParameter = document_HeadId.HasValue ?
                new ObjectParameter("Document_HeadId", document_HeadId) :
                new ObjectParameter("Document_HeadId", typeof(long));
    
            var document_Head2IdParameter = document_Head2Id.HasValue ?
                new ObjectParameter("Document_Head2Id", document_Head2Id) :
                new ObjectParameter("Document_Head2Id", typeof(long));
    
            var dMonthParameter = dMonth.HasValue ?
                new ObjectParameter("DMonth", dMonth) :
                new ObjectParameter("DMonth", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCommericalDocuments_Result>("GetCommericalDocuments", company_IDParameter, document_HeadIdParameter, document_Head2IdParameter, dMonthParameter);
        }
    
        public virtual ObjectResult<GetProjectsEmployee_Result> GetProjectsEmployee(Nullable<long> project_Id)
        {
            var project_IdParameter = project_Id.HasValue ?
                new ObjectParameter("Project_Id", project_Id) :
                new ObjectParameter("Project_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectsEmployee_Result>("GetProjectsEmployee", project_IdParameter);
        }
    
        public virtual ObjectResult<SalarySlipDetail_Result> SalarySlipDetail(Nullable<long> projectSalaryID)
        {
            var projectSalaryIDParameter = projectSalaryID.HasValue ?
                new ObjectParameter("ProjectSalaryID", projectSalaryID) :
                new ObjectParameter("ProjectSalaryID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalarySlipDetail_Result>("SalarySlipDetail", projectSalaryIDParameter);
        }
    
        public virtual ObjectResult<spAllEmployeeList_Result> spAllEmployeeList(Nullable<long> companyId, Nullable<long> userType)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(long));
    
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllEmployeeList_Result>("spAllEmployeeList", companyIdParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spCountDashboard_Result> spCountDashboard(Nullable<long> company_ID, Nullable<long> user_type)
        {
            var company_IDParameter = company_ID.HasValue ?
                new ObjectParameter("Company_ID", company_ID) :
                new ObjectParameter("Company_ID", typeof(long));
    
            var user_typeParameter = user_type.HasValue ?
                new ObjectParameter("User_type", user_type) :
                new ObjectParameter("User_type", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCountDashboard_Result>("spCountDashboard", company_IDParameter, user_typeParameter);
        }
    
        public virtual ObjectResult<spHiredEmployeeList_Result> spHiredEmployeeList(Nullable<long> companyID, Nullable<long> userType)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(long));
    
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spHiredEmployeeList_Result>("spHiredEmployeeList", companyIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spPresentEmployee_Result> spPresentEmployee(Nullable<long> companyID, Nullable<long> userType)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(long));
    
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPresentEmployee_Result>("spPresentEmployee", companyIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<GetCompanyPunchDetails_Result> GetCompanyPunchDetails(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> companyId, Nullable<decimal> fullDayHrs, Nullable<decimal> halfDayHrs)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var fullDayHrsParameter = fullDayHrs.HasValue ?
                new ObjectParameter("FullDayHrs", fullDayHrs) :
                new ObjectParameter("FullDayHrs", typeof(decimal));
    
            var halfDayHrsParameter = halfDayHrs.HasValue ?
                new ObjectParameter("HalfDayHrs", halfDayHrs) :
                new ObjectParameter("HalfDayHrs", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompanyPunchDetails_Result>("GetCompanyPunchDetails", fromDateParameter, toDateParameter, companyIdParameter, fullDayHrsParameter, halfDayHrsParameter);
        }
    
        public virtual ObjectResult<GetUserPunchDetails_Result> GetUserPunchDetails(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> userId, Nullable<decimal> fullDayHrs, Nullable<decimal> halfDayHrs)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var fullDayHrsParameter = fullDayHrs.HasValue ?
                new ObjectParameter("FullDayHrs", fullDayHrs) :
                new ObjectParameter("FullDayHrs", typeof(decimal));
    
            var halfDayHrsParameter = halfDayHrs.HasValue ?
                new ObjectParameter("HalfDayHrs", halfDayHrs) :
                new ObjectParameter("HalfDayHrs", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserPunchDetails_Result>("GetUserPunchDetails", fromDateParameter, toDateParameter, userIdParameter, fullDayHrsParameter, halfDayHrsParameter);
        }
    
        public virtual ObjectResult<Admin_Dashboard_Result> Admin_Dashboard(Nullable<long> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_Dashboard_Result>("Admin_Dashboard", companyIDParameter);
        }
    }
}
