//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Master
    {
        public long Doc_Id { get; set; }
        public long Company_ID { get; set; }
        public long User_Id { get; set; }
        public string Doc_Path { get; set; }
        public string Doc_Type { get; set; }
        public string Doc_Name { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
