//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Master
    {
        public long Edu_Id { get; set; }
        public long User_Id { get; set; }
        public string Edu_Name { get; set; }
        public string university { get; set; }
        public string Pass_Out { get; set; }
        public Nullable<long> Status { get; set; }
        public string Field { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
