//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Task_Master
    {
        public long Employee_Task_id { get; set; }
        public Nullable<long> User_id { get; set; }
        public string Task_Detail { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
