//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Master
    {
        public long Event_Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public Nullable<long> added_by { get; set; }
        public long Company_ID { get; set; }
        public Nullable<long> User_id { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
