//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience_Master
    {
        public long Exp_Id { get; set; }
        public long User_Id { get; set; }
        public string Last_Company { get; set; }
        public string working_years { get; set; }
        public string Last_Year { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
