//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp_Master
    {
        public long FollowUp_ID { get; set; }
        public Nullable<long> Inquiry_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Next_followed_Date { get; set; }
        public string Longitutde { get; set; }
        public string Latitude { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Added_on { get; set; }
        public Nullable<long> Added_by { get; set; }
    
        public virtual Inquiry_Master Inquiry_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
