//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generated_Documents
    {
        public long Gen_doc_id { get; set; }
        public string Gen_doc_no { get; set; }
        public Nullable<long> Gen_doc_empid { get; set; }
        public string Gen_doc_text { get; set; }
        public string Gen_doc_Title { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
