//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift_Master
    {
        public long Gift_Id { get; set; }
        public long Company_ID { get; set; }
        public long User_Id { get; set; }
        public Nullable<long> Festival_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Gift_Name { get; set; }
        public string Gift_Desc { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual Festival_Master Festival_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
