//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday_Master
    {
        public long Holiday_Id { get; set; }
        public long Company_Id { get; set; }
        public string Holiday_Name { get; set; }
        public Nullable<System.DateTime> Holiday_Date { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
