//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquiry_Master()
        {
            this.FollowUp_Master = new HashSet<FollowUp_Master>();
        }
    
        public long Inquiry_Id { get; set; }
        public string Inquiry_Name { get; set; }
        public long Mobile_no { get; set; }
        public string Email_Id { get; set; }
        public string Services { get; set; }
        public System.DateTime Previous_meeting { get; set; }
        public System.DateTime Next_meeting { get; set; }
        public Nullable<int> Lead_Status { get; set; }
        public string CreatyedBy { get; set; }
        public Nullable<long> Assign_To { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Added_on { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<long> assighnNextID { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUp_Master> FollowUp_Master { get; set; }
    }
}
