//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Master
    {
        public long leave_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Leave_Crdr { get; set; }
        public long User_Id { get; set; }
        public Nullable<decimal> leave_days { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public string Leave_Type { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> F_Date { get; set; }
        public Nullable<int> T_Date { get; set; }
        public string Remark { get; set; }
        public System.DateTime ReqDate { get; set; }
        public Nullable<long> Add_By { get; set; }
        public Nullable<long> Approved_By { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
    }
}
