//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Token
    {
        public long access_id { get; set; }
        public long User_ID { get; set; }
        public string Token { get; set; }
        public string Public_key { get; set; }
        public string Private_key { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime Expire { get; set; }
        public string Mac_Address { get; set; }
        public string Device_Address { get; set; }
        public string FCM_DeviceID { get; set; }
        public string langitute { get; set; }
        public string lantitute { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
