//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Task_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Task_Master()
        {
            this.Comment_Master = new HashSet<Comment_Master>();
        }
    
        public long Task_Id { get; set; }
        public long Emp_Id { get; set; }
        public string Cost_Center { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public string Task_Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Actual_Start_Date { get; set; }
        public Nullable<System.DateTime> Actual_End_Date { get; set; }
        public string Person { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<int> Status { get; set; }
        public string Approved_By { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public Nullable<System.DateTime> Revised_Start_Date { get; set; }
        public Nullable<System.DateTime> Revised_End_Date { get; set; }
        public Nullable<long> Task_No { get; set; }
        public Nullable<long> Task_Type { get; set; }
        public string UI_flag { get; set; }
        public string Priority { get; set; }
        public Nullable<long> Complete { get; set; }
        public Nullable<long> Duration { get; set; }
        public string Duration_Unit { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> O_End_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Master> Comment_Master { get; set; }
        public virtual Project_Master Project_Master { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
