//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSalaryHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectSalaryHead()
        {
            this.ProjectSalaries = new HashSet<ProjectSalary>();
        }
    
        public long ProjectSalaryHeadID { get; set; }
        public long Company_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public int DailyHours { get; set; }
        public string OTRate { get; set; }
        public string BASIC { get; set; }
        public string HRA { get; set; }
        public string DA { get; set; }
        public string LEAVE { get; set; }
        public string BONUS { get; set; }
        public string TA { get; set; }
        public string PH { get; set; }
        public string SPECIALALLOWANCE { get; set; }
        public string OTHERALLOWANCE { get; set; }
        public string PF { get; set; }
        public string PT { get; set; }
        public string ESIC { get; set; }
        public string CANTEEN { get; set; }
        public string HRA_DEDUCT { get; set; }
        public string TRAVEL { get; set; }
        public string ADVANCE { get; set; }
        public string Uniform { get; set; }
        public string Welfare { get; set; }
        public string Other { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSalary> ProjectSalaries { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
