//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSalary
    {
        public long ProjectSalaryID { get; set; }
        public long ProjectSalaryHeadID { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public long User_ID { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int NoOfDays { get; set; }
        public int NoOfPH { get; set; }
        public int NoOfOTHors { get; set; }
        public int ShiftHours { get; set; }
        public int NoOfOTShift { get; set; }
        public Nullable<decimal> BASIC { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> PHRate { get; set; }
        public Nullable<decimal> MinWagesPerDay { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> LEAVE { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> OTPAYMENT { get; set; }
        public Nullable<decimal> SPECIALALLOWANCE { get; set; }
        public Nullable<decimal> OTHERALLOWANCE { get; set; }
        public Nullable<decimal> GROSS_INCOME { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> PT { get; set; }
        public Nullable<decimal> ESIC { get; set; }
        public Nullable<decimal> CANTEEN { get; set; }
        public Nullable<decimal> HRA_DEDUCT { get; set; }
        public Nullable<decimal> TRAVEL { get; set; }
        public Nullable<decimal> ADVANCE { get; set; }
        public Nullable<decimal> Uniform { get; set; }
        public Nullable<decimal> Welfare { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> GROSS_DEDUCTION { get; set; }
        public Nullable<decimal> NET_INCOME { get; set; }
    
        public virtual ProjectSalaryHead ProjectSalaryHead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
