//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Assign_Master
    {
        public long Project_Assign_Id { get; set; }
        public long Project_Id { get; set; }
        public long Emp_Id { get; set; }
    
        public virtual Project_Master Project_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
