//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation_Master
    {
        public long Relation_Id { get; set; }
        public long User_Id { get; set; }
        public string Relation_Name { get; set; }
        public string Person_Name { get; set; }
        public Nullable<long> Mobile_No { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
