//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_Master()
        {
            this.Voucher_Master = new HashSet<Voucher_Master>();
        }
    
        public long Req_Id { get; set; }
        public Nullable<long> Status { get; set; }
        public long User_Id { get; set; }
        public string Description { get; set; }
        public Nullable<long> Voucher_No { get; set; }
        public string Place { get; set; }
        public string Remark { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public System.DateTime A_Date { get; set; }
        public System.DateTime S_Date { get; set; }
        public System.DateTime E_Date { get; set; }
        public Nullable<decimal> Requested_Amount { get; set; }
        public Nullable<decimal> Granted_Amount { get; set; }
        public string Parent_Type { get; set; }
        public string Remark_For_Admin { get; set; }
        public System.DateTime ReqDate { get; set; }
    
        public virtual Project_Master Project_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher_Master> Voucher_Master { get; set; }
    }
}
