//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resignation_Master
    {
        public long Resignation_Id { get; set; }
        public Nullable<long> Emp_Id { get; set; }
        public Nullable<System.DateTime> Date_Of_Resignation { get; set; }
        public Nullable<long> Designation { get; set; }
        public Nullable<System.DateTime> Date_Of_Join { get; set; }
        public string Team_Name { get; set; }
        public Nullable<long> Department { get; set; }
        public Nullable<System.DateTime> Reliving_Date { get; set; }
        public string Reason_For_Exit { get; set; }
        public string Remark_For_Resignation { get; set; }
        public string Suggestion_For_Company { get; set; }
        public Nullable<long> HR_Authority { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark_For_Managment { get; set; }
        public Nullable<long> Reporting_Person { get; set; }
    
        public virtual Department_Master Department_Master { get; set; }
        public virtual Designation_Master Designation_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
    }
}
