//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Master
    {
        public long Trans_id { get; set; }
        public long User_id { get; set; }
        public long Type_id { get; set; }
        public decimal Amount { get; set; }
        public string Type_Name { get; set; }
        public string Ref_Id { get; set; }
        public System.DateTime Trans_Date { get; set; }
        public Nullable<long> Head_Id { get; set; }
        public Nullable<long> Forwerded { get; set; }
        public string Description { get; set; }
    
        public virtual Head_Master Head_Master { get; set; }
        public virtual Transaction_Master Transaction_Master1 { get; set; }
        public virtual Transaction_Master Transaction_Master2 { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
