//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.Address_Master = new HashSet<Address_Master>();
            this.Asset_Movement = new HashSet<Asset_Movement>();
            this.Asset_Movement1 = new HashSet<Asset_Movement>();
            this.Attendance_Master = new HashSet<Attendance_Master>();
            this.Comment_Master = new HashSet<Comment_Master>();
            this.Comment_Master1 = new HashSet<Comment_Master>();
            this.Document_Master = new HashSet<Document_Master>();
            this.Education_Master = new HashSet<Education_Master>();
            this.Employee_Task_Master = new HashSet<Employee_Task_Master>();
            this.Event_Master = new HashSet<Event_Master>();
            this.Experience_Master = new HashSet<Experience_Master>();
            this.FollowUp_Master = new HashSet<FollowUp_Master>();
            this.Generated_Documents = new HashSet<Generated_Documents>();
            this.Gift_Master = new HashSet<Gift_Master>();
            this.Imp_Doc_Master = new HashSet<Imp_Doc_Master>();
            this.Leave_Master = new HashSet<Leave_Master>();
            this.Leave_Master1 = new HashSet<Leave_Master>();
            this.Leave_Master2 = new HashSet<Leave_Master>();
            this.Master_Token = new HashSet<Master_Token>();
            this.Project_Assign_Master = new HashSet<Project_Assign_Master>();
            this.Project_Task_Master = new HashSet<Project_Task_Master>();
            this.ProjectSalaries = new HashSet<ProjectSalary>();
            this.ProjectSalaryHeads = new HashSet<ProjectSalaryHead>();
            this.Relation_Master = new HashSet<Relation_Master>();
            this.Request_Master = new HashSet<Request_Master>();
            this.Resignation_Master = new HashSet<Resignation_Master>();
            this.Resignation_Master1 = new HashSet<Resignation_Master>();
            this.Resignation_Master2 = new HashSet<Resignation_Master>();
            this.Transaction_Master = new HashSet<Transaction_Master>();
            this.User_Menu_Rights = new HashSet<User_Menu_Rights>();
            this.User_Punch = new HashSet<User_Punch>();
            this.User_Visits = new HashSet<User_Visits>();
            this.UserMaster1 = new HashSet<UserMaster>();
            this.Voucher_Master = new HashSet<Voucher_Master>();
        }
    
        public long User_ID { get; set; }
        public long Company_ID { get; set; }
        public string EmployeeID { get; set; }
        public string User_UID { get; set; }
        public string User_Name { get; set; }
        public long User_Mobile { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public Nullable<long> User_type { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> RefMobile { get; set; }
        public string image_path { get; set; }
        public string image_name { get; set; }
        public string City_Name { get; set; }
        public string Religion_name { get; set; }
        public string Blood_group { get; set; }
        public Nullable<long> Adharcard_No { get; set; }
        public string PanCard_No { get; set; }
        public decimal Total_PL { get; set; }
        public decimal Total_CL { get; set; }
        public decimal Total_EL { get; set; }
        public decimal Total_Leave { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime Date_of_join { get; set; }
        public string Alter_Email { get; set; }
        public string Company_Email { get; set; }
        public Nullable<long> Depart_id { get; set; }
        public Nullable<long> Desig_id { get; set; }
        public string Posted_At { get; set; }
        public string Team_name { get; set; }
        public string Bank_Acc_No { get; set; }
        public string IFSC_No { get; set; }
        public string Bank_Name { get; set; }
        public string EC_No { get; set; }
        public string UAN_No { get; set; }
        public string ESIC_No { get; set; }
        public string PF_No { get; set; }
        public Nullable<long> last_otp { get; set; }
        public Nullable<System.DateTime> last_otp_expire { get; set; }
        public Nullable<long> Reporting_Person { get; set; }
        public Nullable<bool> Profile_Lock { get; set; }
        public Nullable<int> SkilledType { get; set; }
        public Nullable<long> Project_SalaryGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address_Master> Address_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Movement> Asset_Movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Movement> Asset_Movement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_Master> Attendance_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Master> Comment_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Master> Comment_Master1 { get; set; }
        public virtual Company_Master Company_Master { get; set; }
        public virtual Department_Master Department_Master { get; set; }
        public virtual Designation_Master Designation_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_Master> Document_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_Master> Education_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Task_Master> Employee_Task_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_Master> Event_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience_Master> Experience_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUp_Master> FollowUp_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Generated_Documents> Generated_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift_Master> Gift_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imp_Doc_Master> Imp_Doc_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Master> Leave_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Master> Leave_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Master> Leave_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master_Token> Master_Token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Assign_Master> Project_Assign_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Task_Master> Project_Task_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSalary> ProjectSalaries { get; set; }
        public virtual ProjectSalaryGroup ProjectSalaryGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSalaryHead> ProjectSalaryHeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation_Master> Relation_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Master> Request_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resignation_Master> Resignation_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resignation_Master> Resignation_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resignation_Master> Resignation_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Master> Transaction_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Menu_Rights> User_Menu_Rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Punch> User_Punch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Visits> User_Visits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMaster> UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher_Master> Voucher_Master { get; set; }
    }
}
