//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Visits
    {
        public long Visit_id { get; set; }
        public long User_Id { get; set; }
        public long PunchType_Id { get; set; }
        public System.DateTime Time { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string LocationName { get; set; }
        public string Location { get; set; }
        public Nullable<long> Punch_Via { get; set; }
        public string IP_Address { get; set; }
        public string image_path { get; set; }
        public string image_name { get; set; }
    
        public virtual Punch_Type Punch_Type { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
