//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickKarmachari
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_Master
    {
        public long Voucher_Id { get; set; }
        public Nullable<long> Req_Id { get; set; }
        public long User_Id { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public System.DateTime Voucher_Date { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<long> Payment_By { get; set; }
        public string Place { get; set; }
        public Nullable<decimal> Petrol { get; set; }
        public Nullable<decimal> Travelling { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Deduction_Amount { get; set; }
        public Nullable<decimal> Payable_Amount { get; set; }
        public Nullable<decimal> Advance_Amount { get; set; }
        public string Parent_Type { get; set; }
        public Nullable<int> Trans_Type { get; set; }
        public string Remark { get; set; }
        public string Remark_For_Administrator { get; set; }
        public string Image_Name { get; set; }
    
        public virtual Project_Master Project_Master { get; set; }
        public virtual Request_Master Request_Master { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
